apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-python-app-deployment
  labels:
    app: simple-python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-python-app
  template:
    metadata:
      labels:
        app: simple-python-app
    spec:
      containers:
      - name: simple-python-app
        image: pavant049/simple-python-flask-app:latest
        ports:
        - containerPort: 80
